apiVersion: v1
kind: Service
metadata:
  name: interview-hub
  labels:
    app: interview-hub
spec:
  type: LoadBalancer
  selector:
    app: interview-hub
  ports:
    - name: http
      port: 80
      targetPort: 80
